blank_issues_enabled: true
contact_links:
  - name: ğŸ’¬ Discussion gÃ©nÃ©rale
    url: https://github.com/GDGToulouse/toulouse-tech-hub/discussions
    about: Posez des questions ou discutez d'idÃ©es pour amÃ©liorer le site
  - name: ğŸŒ Site web
    url: https://toulouse-tech-hub.fr
    about: Consultez le site Toulouse Tech Hub
